### ISSUE TITLE
samtools hard-coded to a gsc-specific path

### ISSUE THREAD

**Issue by ckeeling** [warrenlr/RAILS#7]
Hi Rene,

I notice that the location of samtools in your shell and perl scripts are hard-coded to a gsc-specific path.

I hope everything is going well with you.  I've been enjoying looking into all these recent genomes you guys have been publishing using 10x data etc.  I hope to make use of these tools and pipelines in the near future.
Cheers,

Chris

**Comment by warrenlr** [comment]
good to hear from you Chris.

Yes, this was initially done for benchmarking and compatibility reasons (exporting $PATH to linuxbrew have caused versioning issues in the past due to symbolic links). We wanted to be consistent for our scaffolding/gap-filling runs, I haven't changed that for the github submission.  

Users may wish to alter the code to reflect the location of these tools on their system or simply replace by "samtools", as long as it is in their path (eg. #linuxbrew
export PATH=/gsc/btl/linuxbrew/bin:$PATH).

All the best,
Rene

**Comment by ckeeling** [comment]
OK thanks.  I mention this because it is not just in the export commands, but in various places within several scripts.  Your beluga path is also referenced. Cheers, Chris

**Comment by warrenlr** [comment]
Thanks Chris, I didn't realize that! fixing this ..

**Comment by warrenlr** [comment]
completely fixed (I think) in v1.4.1 (released).

**Comment by ckeeling** [comment]
👍
